In [7]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import neighbors
from sklearn import model_selection 

In [8]:
digits = load_digits()#载入数据
x_data = digits.data#数据
y_data = digits.target#标签
#输入数据归一化
x_data -= x_data.min()
x_data /= x_data.max()

x_train,x_test,y_train,y_test = train_test_split(x_data, y_data, test_size=0.2) #分割数据0.2为测试数据，0.8为训练数据

In [9]:
# 构建模型
model = neighbors.KNeighborsClassifier(n_neighbors=5)
model.fit(x_train, y_train)
predictions = model.predict(x_test)

print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        35
          1       0.94      1.00      0.97        31
          2       1.00      1.00      1.00        36
          3       1.00      0.95      0.98        44
          4       0.97      1.00      0.99        34
          5       0.97      1.00      0.98        32
          6       1.00      1.00      1.00        38
          7       0.98      1.00      0.99        41
          8       0.97      0.97      0.97        36
          9       0.97      0.88      0.92        33

avg / total       0.98      0.98      0.98       360



In [10]:
print(confusion_matrix(y_test, predictions))

[[35  0  0  0  0  0  0  0  0  0]
 [ 0 31  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 42  0  0  0  1  0  1]
 [ 0  0  0  0 34  0  0  0  0  0]
 [ 0  0  0  0  0 32  0  0  0  0]
 [ 0  0  0  0  0  0 38  0  0  0]
 [ 0  0  0  0  0  0  0 41  0  0]
 [ 0  1  0  0  0  0  0  0 35  0]
 [ 0  1  0  0  1  1  0  0  1 29]]
