In [3]:
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix
import numpy as np

In [7]:
data = np.genfromtxt('wine_data.csv', delimiter=',')

In [17]:
x_data = data[:,1:]
x_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [10]:
y_data = data[:,0]

In [11]:
print(x_data.shape)

(178, 13)


In [13]:
print(y_data. shape)

(178,)


In [14]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data)

In [15]:
x_train

array([[1.383e+01, 1.570e+00, 2.620e+00, ..., 1.130e+00, 2.570e+00,
        1.130e+03],
       [1.281e+01, 2.310e+00, 2.400e+00, ..., 6.600e-01, 1.360e+00,
        5.600e+02],
       [1.225e+01, 1.730e+00, 2.120e+00, ..., 1.000e+00, 3.170e+00,
        5.100e+02],
       ...,
       [1.351e+01, 1.800e+00, 2.650e+00, ..., 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.340e+01, 3.910e+00, 2.480e+00, ..., 7.000e-01, 1.560e+00,
        7.500e+02],
       [1.324e+01, 2.590e+00, 2.870e+00, ..., 1.040e+00, 2.930e+00,
        7.350e+02]])

In [25]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [33]:
mlp = MLPClassifier(hidden_layer_sizes=(100, 50),max_iter=500)
mlp.fit(x_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [37]:
predictions = mlp.predict(x_test)
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        1.0       1.00      1.00      1.00        12
        2.0       0.94      0.94      0.94        18
        3.0       0.93      0.93      0.93        15

avg / total       0.96      0.96      0.96        45



In [38]:
print(confusion_matrix(y_test,predictions))

[[12  0  0]
 [ 0 17  1]
 [ 0  1 14]]
